// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzlotgkzipwukdjfbaso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6bG90Z2t6aXB3dWtkamZiYXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjIyMjQsImV4cCI6MjA1ODc5ODIyNH0.t3fqUrQPxN07o0JoE2VFIklHFxWHtp7IE_116IXIX0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);